log:
  logLevel: "info"  
  logPath: "./logs"
  logFileName: "mmc.log"
  logFileRotationHours: 24
  logFileMaxAgeHours: 240
db:
  driverName: "mysql"
  dataSourceName: "{user}:{password}@tcp({ip}:{port})/{db}"