log:
  logLevel: "info"  
  logPath: "./logs"
  logFileName: "mmc.log"
  logFileRotationHours: 24
  logFileMaxAgeHours: 240
db:
  driverName: "mysql"
  dataSourceName: "{user}:{password}@tcp({ip}:{port})/{db}"
  dataBase: "{db}"
java:
  templateFolder: "./templates/java"
  outputFolder: "./output/java"
  basePackage: "{base-package}"
  ignorePrefix: ""
  ignoreSuffix: ""
  ignoreColumns:
    - "TransactionNumber"
    - "inUser"
