log:
  logLevel: "info"  
  logPath: "./logs"
  logFileName: "mmc.log"
  logFileRotationHours: 24
  logFileMaxAgeHours: 240
db:
  driverName: "mysql"
  dataSourceName: "{user}:{password}@tcp({ip}:{port})/{db}"
  dataBase: "{db}"
java:
  templateFolder: "./templates/java"
  outputFolder: "./output/java"
  modelSubFolder: "model"
  daoSubFolder: "mapper"
  author: "mmc"
  version: "Version 1.0"
  basePackage: "{base-package}"
  ignorePrefix: "test_"
  ignoreSuffix: "_test"
  includeTableRegex: ""
  excludeTableRegex: ""
  updateStatementIgnoreColumns:
    - "TransactionNumber"
    - "Version"
    - "InUser"
    - "InDate"
    - "Deleted"
  deleteStatementIgnoreColumns:
    - "InUser"
    - "InDate"
    - "LastEditUser"
    - "LastEditDate"
    - "Deleted"